version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://localhost:8080
      - HOST=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules